import Link from "next/link";

const sections = [
  ["Offer", "Founder Above the Fold has one current public offer: the one-time CA$7,500 Founder Above the Fold Transformation, internally labelled founder_transformation. The retired low-price Mac, profile-setup, SaaS and visibility-ops offers are not available for purchase."],
  ["Transformation scope", "The package includes one intake or kickoff, founder positioning and above-the-fold credibility repair, an assembled headline, About section, Experience recommendations and Featured-section plan, a founder signal map, voice guide, ten launch post drafts, the private macOS and web operating workbench, one consolidated revision round requested within seven calendar days, and final handover."],
  ["Delivery boundary", "The engagement ends at final handover or fourteen calendar days after initial delivery if no revision request is supplied. It does not include continuing posting, monthly management, unlimited revisions, direct-message campaigns, advertising, design production, photography, video, legal review or later updates unless separately agreed in writing."],
  ["No silent scope expansion", "Customer delays do not create open-ended availability. Extra posts, meetings, revision rounds, post-approval rewrites, messages, comments, lead generation, community management, crisis work, same-day work or work for another person or brand require a separate written quote or an agreed substitution. Phrases such as 'one more thing', 'quick question' or 'it will only take a second' do not change the purchased scope."],
  ["Written additions only", "Additional work begins only after both sides agree in writing to the deliverables, price and delivery date. Courtesy, silence, prior exceptions and informal conversations do not amend the order. No additional consumer charge is made without express agreement, and mandatory consumer rights are preserved."],
  ["Mac licence", "The transformation includes one owned macOS licence for the stated major version and device allowance. It is part of the transformation package, not a separately purchasable low-price product. Supported macOS versions, update period, device allowance and any later paid major upgrade must match the checkout and reviewed launch terms."],
  ["Owner responsibility", "You decide what to draft, retain, export, and manually place on LinkedIn. You are responsible for checking factual claims, permissions, intellectual property, and the destination platform’s rules."],
  ["Safety boundary", "The product does not promise automated LinkedIn profile changes, scraping, direct messages, follows, likes, comments, reposts, or browser automation. Publishing remains intentionally locked until a separately approved, official integration is proven."],
  ["Local AI and voice", "Voice transcripts and optional local AI are drafting tools, not sources of truth. Availability varies by device and operating system. Review output before using it publicly."],
  ["Payments and refunds", "No live payment rail is active yet. Stripe is fitted only in sandbox mode for the proposed direct web checkout; Apple commerce is not the launch rail. The app must unlock only from a server-verified licence receipt. Full refunds mark the licence refunded, and disputes suspend or revoke it according to the provider outcome. Final tax, refund, chargeback, consumer-rights, and support wording must be legally reviewed before sale."],
  ["Changes and contact", "Material changes will be dated and shown before they apply. A verified support and privacy contact must be inserted before public launch."],
] as const;

export default function TermsPage() {
  return <main className="min-h-screen bg-[#f7f1df] text-[#111]"><section className="mx-auto w-full max-w-[1000px] px-5 py-10 lg:px-8"><Link className="text-sm font-black uppercase underline" href="/product">Back to product screens</Link><span className="cut-label mt-7 bg-[#f4d13d]">Draft for launch fitting · 28 July 2026</span><h1 className="mt-6 text-5xl font-black uppercase leading-none md:text-7xl">Terms of use</h1><p className="mt-5 max-w-3xl text-lg font-semibold leading-8">These terms describe the one-time Founder Above the Fold Transformation and its strict delivery boundary. They are a product draft, not a substitute for Canadian legal review or the final storefront terms.</p><div className="mt-9 grid gap-4">{sections.map(([title,body],i)=><article className="paper-card p-5" key={title}><span className="section-kicker">Part {String(i+1).padStart(2,"0")}</span><h2 className="mt-2 text-2xl font-black uppercase">{title}</h2><p className="mt-3 leading-7">{body}</p></article>)}</div><div className="warning-strip mt-7"><strong>Launch clamp:</strong><span>Insert the legal entity name, support address, governing law, checkout/refund terms, and verified effective date before selling.</span></div></section></main>;
}
