import Link from "next/link";

const sections = [
  ["Offers", "Founder Above the Fold has four separate offers: a one-time macOS licence, one-time LinkedIn Profile Setup, monthly self-serve Founder Profile OS, and monthly Founder Visibility Ops. The selected checkout order controls the purchased offer. Buying one offer does not include another unless the checkout expressly says so."],
  ["Profile Setup scope", "The one-time CA$499 Profile Setup includes one intake or kickoff, one profile package containing a headline, About section, Experience recommendations, featured-link plan, founder content pillars and ten initial post drafts, one consolidated revision round requested within seven calendar days, and one final handover. The service ends at final handover or fourteen calendar days after initial delivery if no revision request is supplied. It does not include continuing posting, monthly management, unlimited revisions or later updates."],
  ["Visibility Ops scope", "Each paid CA$750 Visibility Ops month includes one content and positioning plan, up to four completed LinkedIn post drafts, one consolidated revision round per included post, one meeting of up to 30 minutes, one profile-positioning review, and queue or publishing support for those posts subject to customer approval and the availability of LinkedIn's permitted official integration. The standard response target is two business days; this is not emergency or same-day service."],
  ["No silent scope expansion", "Included work and meeting time expire at the end of each billing month and do not roll over or become credit. Customer delays do not extend the month. Extra posts, meetings, revision rounds, post-approval rewrites, messages, comments, lead generation, community management, crisis work, same-day work, design, photography, video, advertising, legal review, factual investigation, account recovery and work for another person or brand require a separate written quote or an agreed substitution. Phrases such as 'one more thing', 'quick question' or 'it will only take a second' do not change the purchased scope."],
  ["Written additions only", "Additional work begins only after both sides agree in writing to the deliverables, price and delivery date. Courtesy, silence, prior exceptions and informal conversations do not amend the order. No additional consumer charge is made without express agreement, and mandatory consumer rights are preserved."],
  ["Mac licence", "The proposed native product is a one-time macOS licence purchased directly from the verified Founder Above the Fold web checkout. The final licence scope, supported macOS versions, update period, device allowance, and any later paid major upgrade must match the checkout and reviewed launch terms."],
  ["Owner responsibility", "You decide what to draft, retain, export, and manually place on LinkedIn. You are responsible for checking factual claims, permissions, intellectual property, and the destination platform’s rules."],
  ["Safety boundary", "The product does not promise automated LinkedIn profile changes, scraping, direct messages, follows, likes, comments, reposts, or browser automation. Publishing remains intentionally locked until a separately approved, official integration is proven."],
  ["Local AI and voice", "Voice transcripts and optional local AI are drafting tools, not sources of truth. Availability varies by device and operating system. Review output before using it publicly."],
  ["Payments and refunds", "No live payment rail is active yet. Stripe is fitted only in sandbox mode for the proposed direct web checkout; Apple commerce is not the launch rail. The app must unlock only from a server-verified licence receipt. Full refunds mark the licence refunded, and disputes suspend or revoke it according to the provider outcome. Final tax, refund, chargeback, consumer-rights, and support wording must be legally reviewed before sale."],
  ["Changes and contact", "Material changes will be dated and shown before they apply. A verified support and privacy contact must be inserted before public launch."],
] as const;

export default function TermsPage() {
  return <main className="min-h-screen bg-[#f7f1df] text-[#111]"><section className="mx-auto w-full max-w-[1000px] px-5 py-10 lg:px-8"><Link className="text-sm font-black uppercase underline" href="/product">Back to product screens</Link><span className="cut-label mt-7 bg-[#f4d13d]">Draft for launch fitting · 19 July 2026</span><h1 className="mt-6 text-5xl font-black uppercase leading-none md:text-7xl">Terms of use</h1><p className="mt-5 max-w-3xl text-lg font-semibold leading-8">These terms describe the four proposed Founder Above the Fold offers, including strict boundaries for one-time and monthly professional services. They are a product draft, not a substitute for Canadian legal review or the final storefront terms.</p><div className="mt-9 grid gap-4">{sections.map(([title,body],i)=><article className="paper-card p-5" key={title}><span className="section-kicker">Part {String(i+1).padStart(2,"0")}</span><h2 className="mt-2 text-2xl font-black uppercase">{title}</h2><p className="mt-3 leading-7">{body}</p></article>)}</div><div className="warning-strip mt-7"><strong>Launch clamp:</strong><span>Insert the legal entity name, support address, governing law, checkout/refund terms, and verified effective date before selling.</span></div></section></main>;
}
